name: 03-composition-via-ajax
on: workflow_dispatch
jobs:
  deploy-to-container-apps:
    runs-on: ubuntu-latest
    steps:
    - name: Set Environment Variables
      run: |
        echo "RESOURCE_GROUP=rg-micro-frontends-in-action-03" >> $GITHUB_ENV
        echo "CONTAINER_REGISTRY=crmicrofrontendsinaction03" >> $GITHUB_ENV
        echo "CONTAINERAPPS_ENVIRONMENT=ca-env-micro-frontends-in-action-03" >> $GITHUB_ENV
        echo "DECIDE_CONTAINERAPP=ca-app-decide" >> $GITHUB_ENV
        echo "INSPIRE_CONTAINERAPP=ca-app-inspire" >> $GITHUB_ENV
      shell: bash
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Log in to Container Registry
      run: |
        az acr login -n ${CONTAINER_REGISTRY}
        az acr update -n ${CONTAINER_REGISTRY} --admin-enabled true
    - name: Deploy Services to Container Apps Enviroment
      run: |
        az extension add --n containerapp --upgrade
    - name: Get Services Ingress
      run: |
        echo 'DECIDE_CONTAINERAPP_INGRESS_JSON<<EOF' >> $GITHUB_ENV
        az containerapp ingress show -n ${DECIDE_CONTAINERAPP} -g ${RESOURCE_GROUP} >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
        echo 'INSPIRE_CONTAINERAPP_INGRESS_JSON<<EOF' >> $GITHUB_ENV
        az containerapp ingress show -n ${INSPIRE_CONTAINERAPP} -g ${RESOURCE_GROUP} >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
      shell: bash
    - name: Configure Services URLs
      run: |
        az containerapp update -n ${DECIDE_CONTAINERAPP} -g ${RESOURCE_GROUP} --set-env-vars INSPIRE_SERVICE_URL=https://${{ fromJSON(INSPIRE_CONTAINERAPP_INGRESS_JSON).fqdn }}
        az containerapp update -n ${INSPIRE_CONTAINERAPP} -g ${RESOURCE_GROUP} --set-env-vars DECIDE_SERVICE_URL=https://${{ fromJSON(DECIDE_CONTAINERAPP_INGRESS_JSON).fqdn }}