name: 08-composition-via-blazor-webassembly-based-web-components
on: workflow_dispatch
env:
  SAMPLE: 08-composition-via-blazor-webassembly-based-web-components
  LOCATION: westeurope
  RESOURCE_GROUP: rg-micro-frontends-in-action-08
  MANAGED_IDENTITY: id-micro-frontends-in-action-08
  CONTAINER_REGISTRY: crmicrofrontendsinaction08
  CONTAINERAPPS_ENVIRONMENT: ca-env-micro-frontends-in-action-08
  DECIDE_CONTAINERAPP: ca-app-decide
  INSPIRE_CONTAINERAPP: ca-app-inspire
  CHECKOUT_CONTAINERAPP: ca-app-checkout
  PROXY_CONTAINERAPP: ca-app-proxy
jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy Infrastructure
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        region: ${{ env.LOCATION }}
        template: ./bicep-modules/micro-frontends-in-action-infrastructure.bicep
        deploymentName: 'micro-frontends-in-action-08'
        parameters: 'resourceGroupName=${{ env.RESOURCE_GROUP }} resourceGroupLocation=${{ env.LOCATION }} managedIdentityName=${{ env.MANAGED_IDENTITY }} containerRegistryName=${{ env.CONTAINER_REGISTRY }} containerAppsEnvironmentName=${{ env.CONTAINERAPPS_ENVIRONMENT }}'
    - name: Log Out From Azure
      run: |
        az logout
        az cache purge
        az account clear
  deliver-images:
    needs: [deploy-infrastructure]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Log in to Container Registry
      run: az acr login -n ${CONTAINER_REGISTRY}
    - name: Build Docker Images
      run: |
        docker build ${SAMPLE}/Demo.AspNetCore.MicroFrontendsInAction.Decide/ -t ${CONTAINER_REGISTRY}.azurecr.io/decide:${{ github.sha }}
        docker build ${SAMPLE}/Demo.AspNetCore.MicroFrontendsInAction.Inspire/ -t ${CONTAINER_REGISTRY}.azurecr.io/inspire:${{ github.sha }}
        docker build ${SAMPLE}/Demo.AspNetCore.MicroFrontendsInAction.Checkout/ -t ${CONTAINER_REGISTRY}.azurecr.io/checkout:${{ github.sha }}
        docker build ${SAMPLE}/Demo.AspNetCore.MicroFrontendsInAction.Proxy/ -t ${CONTAINER_REGISTRY}.azurecr.io/proxy:${{ github.sha }}
    - name: Push Docker Images to Container Registry
      run: |
        docker push ${CONTAINER_REGISTRY}.azurecr.io/decide:${{ github.sha }}
        docker push ${CONTAINER_REGISTRY}.azurecr.io/inspire:${{ github.sha }}
        docker push ${CONTAINER_REGISTRY}.azurecr.io/checkout:${{ github.sha }}
        docker push ${CONTAINER_REGISTRY}.azurecr.io/proxy:${{ github.sha }}
    - name: Log Out From Azure
      run: |
        docker logout
        az logout
        az cache purge
        az account clear
  deploy-container-apps:
    needs: [deploy-infrastructure, deliver-images]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy Container Apps
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        resourceGroupName: ${{ env.RESOURCE_GROUP }}
        template: ./bicep-modules/micro-frontends-in-action-deployment.bicep
        deploymentName: 'micro-frontends-in-action-04-cd'
        parameters: 'location=${{ env.LOCATION }} managedIdentityName=${{ env.MANAGED_IDENTITY }} containerRegistryName=${{ env.CONTAINER_REGISTRY }} containerAppsEnvironmentName=${{ env.CONTAINERAPPS_ENVIRONMENT }} microFrontendsContainerAppsDetails="[{\"name\":\"${{ env.DECIDE_CONTAINERAPP }}\",\"imageName\":\"decide\",\"imageTag\":\"${{ github.sha }}\",\"port\":3001,\"urlVariableName\":\"DECIDE_SERVICE_URL\"},{\"name\":\"${{ env.INSPIRE_CONTAINERAPP }}\",\"imageName\":\"inspire\",\"imageTag\":\"${{ github.sha }}\",\"port\":3002,\"urlVariableName\":\"INSPIRE_SERVICE_URL\"},{\"name\":\"${{ env.CHECKOUT_CONTAINERAPP }}\",\"imageName\":\"checkout\",\"imageTag\":\"${{ github.sha }}\",\"port\":3003,\"urlVariableName\":\"CHECKOUT_SERVICE_URL\"}]" microFrontendsProxyContainerAppDetails="{\"name\":\"${{ env.PROXY_CONTAINERAPP }}\",\"imageName\":\"proxy\",\"imageTag\":\"${{ github.sha }}\",\"port\":3000}"'
    - name: Log Out From Azure
      run: |
        az logout
        az cache purge
        az account clear